### PR TITLE
Chandrashekhar_edit_account_information

### PR DESCRIPTION
**Pull request by shekhar1997-chanu**
Hi, Deval
     Please find my updated scripts related to edit info, review and approve the code.

Thanks
Chandrashekhar

### CODE REVIEW

**Comment by Chandrashekhar-Maggidi** [comment]
Hi, Chandrashekhar
  Please add testng assertions.

Thanks 
Deval

**Comment by shekhar1997-chanu** [comment]
Hi, Deval 
Please check updated code and review it.

Thanks 
Chandrashekhar

**Comment by Chandrashekhar-Maggidi** [comment]
Hi, Chandrashekhar
    Just review the code and its good, Please merge the code to master branch
Thanks
Deval

**Comment by shekhar1997-chanu** [comment]
Hi, Deval
 I will merge with master branch 
Thanks 
Chandrashekhar

**Pull request merged**
